# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\PSoc_Folder\ADC_LCD\ADC_LCD.cydsn\ADC_LCD.cyprj
# Date: Fri, 28 Aug 2015 02:18:26 GMT
#set_units -time ns
create_clock -name {ClockBlock/clk_bus} -period 41.666666666666664 -waveform {0 20.8333333333333} [get_pins {ClockBlock/clk_bus}]
create_clock -name {ClockBlock/dclk_0} -period 83.333333333333329 -waveform {0 41.6666666666667} [get_pins {ClockBlock/dclk_0}]
create_clock -name {ClockBlock/dclk_1} -period 333.33333333333331 -waveform {0 166.666666666667} [get_pins {ClockBlock/dclk_1}]
create_clock -name {ClockBlock/dclk_2} -period 958.33333333333326 -waveform {0 479.166666666667} [get_pins {ClockBlock/dclk_2}]
create_clock -name {ClockBlock/aclk_0} -period 3916.6666666666665 -waveform {0 1958.33333333333} [get_pins {ClockBlock/aclk_0}]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CapSense_IntClock} -source [get_pins {ClockBlock/clk_sync}] -divide_by 2 -duty_cycle 50 [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -divide_by 8 -duty_cycle 50 [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {ADC_DelSig_1_Ext_CP_Clk} -source [get_pins {ClockBlock/clk_sync}] -edges {1 23 47} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {ADC_DelSig_1_theACLK} -source [get_pins {ClockBlock/clk_sync}] -divide_by 94 -duty_cycle 50 [list [get_pins {ClockBlock/aclk_glb_0}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -duty_cycle 50 [list [get_pins {ClockBlock/clk_bus_glb}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for D:\PSoc_Folder\ADC_LCD\ADC_LCD.cydsn\TopDesign\TopDesign.cysch
# Project: D:\PSoc_Folder\ADC_LCD\ADC_LCD.cydsn\ADC_LCD.cyprj
# Date: Fri, 28 Aug 2015 02:18:18 GMT
