/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <ADC_DelSig_1.h>
#include <POT_aliases.h>
#include <LCD_Char_1.h>
#include <CapSense.h>
#include <CapSense_CSHL.h>
#include <CapSense_Pins.h>
#include <CapSense_TunerHelper.h>
#include <PWM_1.h>
#include <Clock_1.h>
#include <COLD.h>
#include <COLD_aliases.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <ADC_DelSig_1_theACLK.h>
#include <ADC_DelSig_1_AMux.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <CapSense_IntClock.h>
#include <CapSense_CompCH0.h>
#include <CapSense_AMuxCH0.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
